# Generated by Django 5.0.6 on 2024-09-06 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '__first__'),
        ('common', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cli053SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estado_id_001', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'SOFT_SKILL',
                'db_table': 'cli_053_soft_skill',
            },
        ),
        migrations.CreateModel(
            name='Cli054HardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estado_id_001', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'HARD_SKILL',
                'db_table': 'cli_054_hard_skill',
            },
        ),
        migrations.CreateModel(
            name='Cli055ProfesionEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estado_id_001', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'PROFESION_ESTUDIO',
                'verbose_name_plural': 'PROFESIONES_ESTUDIOS',
                'db_table': 'cli_055_profesion_estudio',
            },
        ),
        migrations.CreateModel(
            name='Cli052Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('numero_posiciones', models.IntegerField()),
                ('experiencia_requerida', models.IntegerField(choices=[(1, '0 a 6 Meses'), (2, '1 año a 2 años'), (3, 'Más de 2 años'), (4, 'Sin Experiencia')])),
                ('funciones_responsabilidades', models.TextField()),
                ('salario', models.IntegerField(blank=True, null=True)),
                ('estado_vacante', models.IntegerField(choices=[(1, 'Abierta'), (2, 'Cerrada'), (3, 'Cancelada')], default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cat004ciudad')),
                ('cliente_id_051', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cli051cliente')),
                ('estado_id_001', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat001estado')),
                ('soft_skills_id_053', models.ManyToManyField(to='vacante.cli053softskill')),
                ('hard_skills_id_054', models.ManyToManyField(to='vacante.cli054hardskill')),
                ('profesion_estudio_id_055', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacante.cli055profesionestudio')),
            ],
            options={
                'verbose_name': 'VACANTE',
                'verbose_name_plural': 'VACANTES',
                'db_table': 'cli_052_vacante',
            },
        ),
    ]
