# Generated by Django 5.0.6 on 2024-09-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacante", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cli052VacanteHardSkillsId054",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "cli_052_vacante_hard_skills_id_054",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cli052VacanteSoftSkillsId053",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "cli_052_vacante_soft_skills_id_053",
                "managed": False,
            },
        ),
    ]
