# Generated by Django 5.0.6 on 2024-09-18 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '__first__'),
        ('vacante', '0002_cli052vacantehardskillsid054_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cli056AplicacionVacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado_aplicacion', models.IntegerField(choices=[(1, 'En proceso'), (2, 'Exitoso'), (3, 'Cancelado'), (4, 'Terminado'), (5, 'Desiste')], default=1)),
                ('candidato_101', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='candidato.can101candidato')),
                ('vacante_id_052', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='vacante.cli052vacante')),
            ],
            options={
                'verbose_name': 'APLICACIÓN A VACANTE',
                'verbose_name_plural': 'APLICACIONES A VACANTES',
                'db_table': 'cli_056_aplicacion_vacante',
                'unique_together': {('candidato_101', 'vacante_id_052')},
            },
        ),
    ]
