# Generated by Django 5.0.6 on 2024-09-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0002_alter_cli052vacante_experiencia_requerida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli052vacante',
            name='experiencia_requerida',
            field=models.IntegerField(choices=[(1, '0 a 6 Meses'), (2, '1 año a 2 años'), (3, 'Más de 2 años')]),
        ),
    ]
