# Generated by Django 5.0.6 on 2024-09-27 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0002_cli057asignacionentrevista'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cli057asignacionentrevista',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cli057asignacionentrevista',
            name='asignacion_vacante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_entrevista', to='vacante.cli056aplicacionvacante'),
        ),
        migrations.RemoveField(
            model_name='cli057asignacionentrevista',
            name='vacante',
        ),
    ]
