# Generated by Django 5.0.6 on 2024-09-27 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0003_alter_cli057asignacionentrevista_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli057asignacionentrevista',
            name='asignacion_vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_entrevista', to='vacante.cli056aplicacionvacante'),
        ),
        migrations.AlterUniqueTogether(
            name='cli057asignacionentrevista',
            unique_together={('asignacion_vacante', 'usuario_asignado', 'fecha_entrevista', 'hora_entrevista')},
        ),
    ]
