# Generated by Django 5.0.6 on 2024-10-12 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_tokenautorizacion_fecha_expiracion'),
        ('vacante', '0004_alter_cli057asignacionentrevista_asignacion_vacante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli057asignacionentrevista',
            name='usuario_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevistas_por_realizar', to='usuarios.usuariobase'),
        ),
        migrations.AlterField(
            model_name='cli057asignacionentrevista',
            name='usuario_asigno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevistas_asignadas', to='usuarios.usuariobase'),
        ),
    ]
