# Generated by Django 5.0.6 on 2024-09-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0004_cli052vacante_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cli052vacante',
            old_name='estado_id_004',
            new_name='estado_id_001',
        ),
    ]
