# Generated by Django 5.0.6 on 2024-09-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0005_rename_estado_id_004_cli052vacante_estado_id_001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cli053softskill',
            old_name='estado_id_004',
            new_name='estado_id_001',
        ),
        migrations.RenameField(
            model_name='cli054hardskill',
            old_name='estado_id_004',
            new_name='estado_id_001',
        ),
        migrations.RenameField(
            model_name='cli055profesionestudio',
            old_name='estado_id_004',
            new_name='estado_id_001',
        ),
    ]
