# Generated by Django 5.0.6 on 2024-10-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0005_alter_cli057asignacionentrevista_usuario_asignado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli052vacante',
            name='estado_vacante',
            field=models.IntegerField(choices=[(1, 'Activa'), (2, 'En Proceso'), (3, 'Finalizada'), (4, 'Cancelada')], default=1),
        ),
    ]
