# Generated by Django 5.0.6 on 2024-09-06 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_cat001estado_nombre_alter_cat001estado_sigla_and_more'),
        ('vacante', '0006_rename_estado_id_004_cli053softskill_estado_id_001_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli052vacante',
            name='estado_id_001',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat001estado'),
        ),
    ]
