# Generated by Django 5.0.6 on 2024-10-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0008_cli063aplicacionvacantehistorial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cli057asignacionentrevista',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='cli063aplicacionvacantehistorial',
            table='cli_063_aplicacion_vacante_historial',
        ),
    ]
