# Generated by Django 5.0.6 on 2024-10-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0009_alter_cli057asignacionentrevista_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli057asignacionentrevista',
            name='fecha_gestion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cli057asignacionentrevista',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='cli057asignacionentrevista',
            name='estado_asignacion',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Apto'), (3, 'No Apto'), (4, 'Seleccionado'), (5, 'Cancelado')], default=1),
        ),
    ]
