# Generated by Django 5.0.6 on 2024-11-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0010_cli057asignacionentrevista_fecha_gestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli056aplicacionvacante',
            name='estado_aplicacion',
            field=models.IntegerField(choices=[(1, 'Aplicado'), (2, 'Entrevista Programada'), (3, 'Entrevista Aprobada'), (4, 'Entrevista No Aprobada'), (5, 'Prueba Programada'), (6, 'Prueba Superada'), (7, 'Prueba No Superada'), (8, 'Seleccionado'), (9, 'Finalizada'), (10, 'Cancelada'), (11, 'Desiste'), (12, 'No Apto')], default=1),
        ),
        migrations.AlterField(
            model_name='cli063aplicacionvacantehistorial',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Aplicado'), (2, 'Entrevista Programada'), (3, 'Entrevista Aprobada'), (4, 'Entrevista No Aprobada'), (5, 'Prueba Programada'), (6, 'Prueba Superada'), (7, 'Prueba No Superada'), (8, 'Seleccionado'), (9, 'Finalizada'), (10, 'Cancelada'), (11, 'Desiste'), (12, 'No Apto')]),
        ),
    ]
