# Generated by Django 5.0.6 on 2024-11-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacante", "0011_alter_cli056aplicacionvacante_estado_aplicacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cli052vacante",
            name="fecha_cierre",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
