# Generated by Django 5.0.6 on 2024-11-08 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('vacante', '0012_cli052vacante_fecha_cierre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli055profesionestudio',
            name='estado_id_001',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.cat001estado'),
        ),
    ]
