# Generated by Django 5.0.6 on 2024-12-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0013_alter_cli055profesionestudio_estado_id_001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cli057AsignacionEntrevista',
        ),
    ]
