# Generated by Django 5.0.6 on 2024-12-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0002_alter_cli057asignacionentrevista_asignacion_vacante'),
        ('vacante', '0014_delete_cli057asignacionentrevista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cli063aplicacionvacantehistorial',
            name='aplicacion_vacante_056',
        ),
        migrations.RemoveField(
            model_name='cli063aplicacionvacantehistorial',
            name='usuario_id_genero',
        ),
        migrations.DeleteModel(
            name='Cli056AplicacionVacante',
        ),
        migrations.DeleteModel(
            name='Cli063AplicacionVacanteHistorial',
        ),
    ]
