# Generated by Django 5.0.6 on 2025-03-06 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_cli068cargo_cli069requisito_and_more'),
        ('common', '0001_initial'),
        ('vacante', '0017_alter_cli052vacante_experiencia_requerida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cli052vacante',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='cli052vacante',
            name='cliente_id_051',
        ),
        migrations.RemoveField(
            model_name='cli052vacante',
            name='experiencia_requerida',
        ),
        migrations.RemoveField(
            model_name='cli052vacante',
            name='funciones_responsabilidades',
        ),
        migrations.RemoveField(
            model_name='cli052vacante',
            name='profesion_estudio_id_055',
        ),
        migrations.RemoveField(
            model_name='cli052vacante',
            name='salario',
        ),
        migrations.AddField(
            model_name='cli052vacante',
            name='asignacion_cliente_id_064',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cli064asignacioncliente'),
        ),
        migrations.AddField(
            model_name='cli052vacante',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cli068cargo'),
        ),
        migrations.CreateModel(
            name='Cli072FuncionesResponsabilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'FUNCION_RESPONSABILIDAD',
                'verbose_name_plural': 'FUNCIONES_RESPONSABILIDADES',
                'db_table': 'cli_072_funciones_responsabilidades',
            },
        ),
        migrations.CreateModel(
            name='Cli073PerfilVacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.CharField(choices=[('1', '19-24 años'), ('2', '25-29 años'), ('3', '30-34 años'), ('4', '35-39 años'), ('5', '40-44 años'), ('6', '45-50 años')], max_length=1)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('tiempo_experiencia', models.IntegerField(choices=[(1, 'Sin experiencia'), (2, '1 año'), (3, '2 años'), (4, '3 años'), (5, '4 años'), (6, '5 años o más')], help_text='Tiempo de experiencia en años')),
                ('horario', models.CharField(max_length=100)),
                ('modalidad', models.CharField(choices=[('R', 'Remoto'), ('P', 'Presencial'), ('H', 'Hibrido')], max_length=1)),
                ('jornada', models.CharField(choices=[('T', 'Diurna'), ('P', 'Nocturna'), ('R', 'Rotativa')], max_length=1)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_salario', models.CharField(choices=[('F', 'Fijo'), ('M', 'Mixto'), ('I', 'Integral'), ('H', 'Por Hora'), ('C', 'Convenio')], max_length=1)),
                ('frecuencia_pago', models.CharField(choices=[('S', 'Semanal'), ('Q', 'Quincenal'), ('M', 'Mensual')], max_length=1)),
                ('salario_adicional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('idioma', models.CharField(max_length=100)),
                ('nivel_estudio', models.IntegerField(choices=[(1, 'Sin estudios'), (2, 'Primaria'), (3, 'Secundaria/Bachillerato'), (4, 'Técnico'), (5, 'Tecnólogo'), (6, 'Universitario'), (7, 'Postgrado')])),
                ('termino_contrato', models.CharField(choices=[('F', 'Fijo'), ('I', 'Indefinido'), ('O', 'Obra Labor')], max_length=1)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.cat001estado')),
                ('lugar_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cat004ciudad')),
                ('profesion_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacante.cli055profesionestudio')),
            ],
            options={
                'verbose_name': 'PERFIL_VACANTE',
                'verbose_name_plural': 'PERFILES_VACANTES',
                'db_table': 'cli_072_perfil_vacante',
            },
        ),
        migrations.CreateModel(
            name='Cli074AsignacionFunciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cat001estado')),
                ('funcion_responsabilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacante.cli072funcionesresponsabilidades')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacante.cli052vacante')),
            ],
            options={
                'verbose_name': 'ASIGNACION_FUNCION',
                'verbose_name_plural': 'ASIGNACIONES_FUNCIONES',
                'db_table': 'cli_074_asignacion_funciones',
                'unique_together': {('vacante', 'funcion_responsabilidad')},
            },
        ),
    ]
