# Generated by Django 5.0.6 on 2025-03-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0019_cli052vacante_perfil_vacante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli052vacante',
            name='descripcion_vacante',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='nivel_idioma',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), (1, 'Sin estudios'), (2, 'Primaria'), (3, 'Secundaria/Bachillerato'), (4, 'Técnico'), (5, 'Tecnólogo'), (6, 'Universitario'), (7, 'Postgrado')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='edad',
            field=models.CharField(choices=[('', 'Seleccione una opción... '), ('7', 'Sin especificar'), ('1', '18-24 años'), ('2', '25-29 años'), ('3', '30-34 años'), ('4', '35-39 años'), ('5', '40-44 años'), ('6', '45-50 años')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='frecuencia_pago',
            field=models.CharField(choices=[('', 'Seleccione una opción...'), ('S', 'Semanal'), ('Q', 'Quincenal'), ('M', 'Mensual')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='genero',
            field=models.CharField(choices=[('', 'Seleccione una opción...'), ('S', 'Sin Especificar'), ('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='jornada',
            field=models.CharField(choices=[('', 'Seleccione una opción...'), ('T', 'Diurna'), ('P', 'Nocturna'), ('R', 'Rotativa')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='modalidad',
            field=models.CharField(choices=[('', 'Seleccione una opción...'), ('R', 'Remoto'), ('P', 'Presencial'), ('H', 'Hibrido')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='nivel_estudio',
            field=models.IntegerField(choices=[('', 'Seleccione una opción...'), (1, 'Sin estudios'), (2, 'Primaria'), (3, 'Secundaria/Bachillerato'), (4, 'Técnico'), (5, 'Tecnólogo'), (6, 'Universitario'), (7, 'Postgrado')]),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='termino_contrato',
            field=models.CharField(choices=[('', 'Seleccione una opción...'), ('F', 'Fijo'), ('I', 'Indefinido'), ('O', 'Obra Labor')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='tiempo_experiencia',
            field=models.IntegerField(choices=[('', 'Seleccione una opción... '), (6, 'Sin Experiencia'), (1, '1 año'), (2, '2 años'), (3, '3 años'), (4, '4 años'), (5, '5 años o más')], help_text='Tiempo de experiencia en años'),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='tipo_salario',
            field=models.CharField(choices=[('', 'Seleccione una opción...'), ('F', 'Fijo'), ('M', 'Mixto'), ('I', 'Integral'), ('H', 'Por Hora'), ('C', 'Convenio')], max_length=1),
        ),
    ]
