# Generated by Django 5.0.6 on 2025-03-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0020_cli052vacante_descripcion_vacante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli052vacante',
            name='estudios_complementarios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cli052vacante',
            name='estudios_complementarios_certificado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='estado_estudio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='hora_final',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='horario_final',
            field=models.CharField(blank=True, choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado'), ('7', 'Domingo')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='horario_inicio',
            field=models.CharField(blank=True, choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado'), ('7', 'Domingo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='nivel_idioma',
            field=models.CharField(blank=True, choices=[('A1', 'A1 - Principiante'), ('A2', 'A2 - Básico'), ('B1', 'B1 - Intermedio'), ('B2', 'B2 - Intermedio Alto'), ('C1', 'C1 - Avanzado'), ('C2', 'C2 - Nativo o Bilingüe')], max_length=2, null=True),
        ),
    ]
