# Generated by Django 5.0.6 on 2025-03-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0021_cli052vacante_estudios_complementarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cli073perfilvacante',
            name='horario',
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='horario_final',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado'), ('7', 'Domingo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='horario_inicio',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado'), ('7', 'Domingo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='nivel_idioma',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('A1', 'A1 - Principiante'), ('A2', 'A2 - Básico'), ('B1', 'B1 - Intermedio'), ('B2', 'B2 - Intermedio Alto'), ('C1', 'C1 - Avanzado'), ('C2', 'C2 - Nativo o Bilingüe')], max_length=2, null=True),
        ),
    ]
