# Generated by Django 5.0.6 on 2025-03-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0022_remove_cli073perfilvacante_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='nivel_estudio',
            field=models.CharField(choices=[('', 'Seleccione una opción...'), (1, 'Sin estudios'), (2, 'Primaria'), (3, 'Secundaria/Bachillerato'), (4, 'Técnico'), (5, 'Tecnólogo'), (6, 'Universitario'), (7, 'Postgrado')]),
        ),
    ]
