# Generated by Django 5.0.6 on 2025-03-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0023_alter_cli073perfilvacante_nivel_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='horario_final',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='horario_inicio',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='nivel_estudio',
            field=models.CharField(choices=[('', 'Seleccione una opción...'), (1, 'Sin estudios'), (2, 'Primaria'), (3, 'Secundaria/Bachillerato'), (4, 'Técnico'), (5, 'Tecnólogo'), (6, 'Universitario'), (7, 'Postgrado')], max_length=1),
        ),
    ]
