# Generated by Django 5.0.6 on 2025-03-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0024_alter_cli073perfilvacante_horario_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli052vacante',
            name='cantidad_presentar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cli052vacante',
            name='fecha_presentacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
