# Generated by Django 5.0.6 on 2025-03-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0025_cli052vacante_cantidad_presentar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='url_mapa',
            field=models.URLField(blank=True, null=True),
        ),
    ]
