# Generated by Django 5.0.6 on 2025-03-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0026_cli073perfilvacante_barrio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cli073perfilvacante',
            name='edad',
        ),
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='edad_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='edad_inicial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='idioma',
            field=models.CharField(choices=[('', 'Seleccione una opción...'), ('ES', 'Español'), ('EN', 'Inglés'), ('FR', 'Francés'), ('DE', 'Alemán'), ('IT', 'Italiano'), ('PT', 'Portugués'), ('RU', 'Ruso'), ('ZH', 'Chino'), ('JP', 'Japonés'), ('AR', 'Árabe'), ('OT', 'Otro')], max_length=100),
        ),
    ]
