# Generated by Django 5.0.6 on 2025-03-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0027_remove_cli073perfilvacante_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='salario_adicional',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='tipo_salario',
            field=models.CharField(choices=[('', 'Seleccione una opción...'), ('F', 'Fijo'), ('M', 'Mixto'), ('I', 'Integral'), ('H', 'Por Hora')], max_length=1),
        ),
    ]
