# Generated by Django 5.0.6 on 2025-04-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0028_alter_cli073perfilvacante_salario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='url_mapa',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
