# Generated by Django 5.0.6 on 2025-07-02 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('vacante', '0029_alter_cli073perfilvacante_url_mapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='nivel_estudio',
            field=models.CharField(choices=[('', 'Seleccione una opción...'), ('1', 'Sin estudios'), ('2', 'Primaria'), ('3', 'Secundaria/Bachillerato'), ('4', 'Técnico'), ('5', 'Tecnólogo'), ('6', 'Universitario'), ('7', 'Postgrado'), ('8', 'Diplomado'), ('9', 'Curso')], max_length=1),
        ),
        migrations.CreateModel(
            name='Cli075GrupoProfesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('estado', models.ForeignKey(db_column='estado_id_001', on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'GRUPO PROFESIÓN',
                'verbose_name_plural': 'GRUPOS PROFESIÓN',
                'db_table': 'cli_075_grupo_profesion',
            },
        ),
    ]
