# Generated by Django 5.0.6 on 2025-07-02 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0030_alter_cli073perfilvacante_nivel_estudio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli055profesionestudio',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacante.cli075grupoprofesion'),
        ),
    ]
