# Generated by Django 5.0.6 on 2025-07-14 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0016_cli078motivadorescandidato'),
        ('vacante', '0031_cli055profesionestudio_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli052vacante',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cli052vacante',
            name='fit_cultural',
            field=models.ManyToManyField(to='cliente.cli077fitcultural'),
        ),
        migrations.AddField(
            model_name='cli052vacante',
            name='motivadores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cli078motivadorescandidato'),
        ),
        migrations.AddField(
            model_name='cli052vacante',
            name='otro_motivador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='estudio_complementario',
            field=models.JSONField(blank=True, help_text='Estudios complementarios en formato JSON', null=True),
        ),
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='experiencia_laboral',
            field=models.JSONField(blank=True, help_text='Experiencia laboral en formato JSON', null=True),
        ),
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='horario',
            field=models.JSONField(blank=True, help_text='Horario de trabajo en formato JSON', null=True),
        ),
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='idiomas',
            field=models.JSONField(blank=True, help_text='Idiomas en formato JSON', null=True),
        ),
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='motivo_vacante',
            field=models.JSONField(blank=True, help_text='Motivo de la vacante en formato JSON', null=True),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='idioma',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('ES', 'Español'), ('EN', 'Inglés'), ('FR', 'Francés'), ('DE', 'Alemán'), ('IT', 'Italiano'), ('PT', 'Portugués'), ('RU', 'Ruso'), ('ZH', 'Chino'), ('JP', 'Japonés'), ('AR', 'Árabe'), ('OT', 'Otro')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='nivel_estudio',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('1', 'Sin estudios'), ('2', 'Primaria'), ('3', 'Secundaria/Bachillerato'), ('4', 'Técnico'), ('5', 'Tecnólogo'), ('6', 'Universitario'), ('7', 'Postgrado'), ('8', 'Diplomado'), ('9', 'Curso')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='profesion_estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacante.cli055profesionestudio'),
        ),
    ]
