# Generated by Django 5.0.6 on 2025-07-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0032_cli052vacante_comentarios_cli052vacante_fit_cultural_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='funciones_responsabilidades',
            field=models.JSONField(blank=True, help_text='Funciones en formato JSON', null=True),
        ),
    ]
