# Generated by Django 5.0.6 on 2025-07-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0021_can107gruposkill_can104skill_grupo'),
        ('vacante', '0033_cli073perfilvacante_funciones_responsabilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli052vacante',
            name='habilidades',
            field=models.ManyToManyField(related_name='habilidades_vacante', to='candidato.can104skill'),
        ),
    ]
