# Generated by Django 5.0.6 on 2025-07-30 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0034_cli052vacante_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='grupo_profesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacante.cli075grupoprofesion'),
        ),
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='profesion_estudio_listado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
