# Generated by Django 5.0.6 on 2025-08-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0035_cli073perfilvacante_grupo_profesion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='tipo_profesion',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('E', 'Profesión Específica'), ('G', 'Grupo de Profesiones'), ('L', 'Listado Personalizado')], max_length=1, null=True),
        ),
    ]
