# Generated by Django 5.0.6 on 2025-10-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0036_cli073perfilvacante_tipo_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='tipo_horario',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('HF', 'Horario Fijo'), ('HX', 'Horario Flexible'), ('HR', 'Horario Rotativo')], help_text='Tipo de horario: Fijo, Rotativo o Flexible', max_length=2, null=True),
        ),
    ]
