# Generated by Django 5.0.6 on 2025-10-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0016_cli078motivadorescandidato'),
        ('vacante', '0037_cli073perfilvacante_tipo_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli052vacante',
            name='motivadores_multiple',
            field=models.ManyToManyField(related_name='motivadores_multiple_vacante', to='cliente.cli078motivadorescandidato'),
        ),
        migrations.RemoveField(
            model_name='cli052vacante',
            name='motivadores',
        ),
        migrations.AddField(
            model_name='cli052vacante',
            name='motivadores',
            field=models.ManyToManyField(related_name='motivadores_vacante', to='cliente.cli078motivadorescandidato'),
        ),
    ]
