# Generated by Django 5.0.6 on 2025-10-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0038_cli052vacante_motivadores_multiple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli073perfilvacante',
            name='cantidad_semestres',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
