# Generated by Django 5.0.6 on 2025-12-16 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0039_cli073perfilvacante_cantidad_semestres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cli052vacante',
            name='asignacion_reclutador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacantes_asignacion_reclutador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cli052vacante',
            name='data_asignacion_reclutador',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cli052vacante',
            name='data_asignacion_usuario',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cli052vacante',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacantes_usuario_asignado', to=settings.AUTH_USER_MODEL),
        ),
    ]
