# Generated by Django 5.0.6 on 2026-03-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacante', '0040_cli052vacante_asignacion_reclutador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli052vacante',
            name='requerimientos_especiales',
            field=models.JSONField(blank=True, help_text='Requerimientos especiales en formato JSON', null=True),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='idioma',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('EN', 'Inglés'), ('FR', 'Francés'), ('DE', 'Alemán'), ('IT', 'Italiano'), ('PT', 'Portugués'), ('RU', 'Ruso'), ('ZH', 'Chino'), ('JP', 'Japonés'), ('AR', 'Árabe')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='nivel_idioma',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('A1', 'A1 - Principiante'), ('A2', 'A2 - Básico'), ('B1', 'B1 - Intermedio'), ('B2', 'B2 - Intermedio Alto'), ('C1', 'C1 - Avanzado'), ('C2', 'C2 - Bilingüe')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cli073perfilvacante',
            name='tiempo_experiencia',
            field=models.IntegerField(choices=[('', 'Seleccione una opción... '), (6, 'Sin Experiencia'), (0, '6 meses'), (1, '1 año'), (2, '2 años'), (3, '3 años'), (4, '4 años'), (5, '5 años o más')], help_text='Tiempo de experiencia en años'),
        ),
    ]
