# Generated by Django 5.0.6 on 2024-07-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat001Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('sigla', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cat_001_estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cat004Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('departamento_id_003', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cat_004_ciudad',
                'managed': False,
            },
        ),
    ]
