# Generated by Django 5.0.6 on 2024-07-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat001estado',
            options={'managed': False, 'verbose_name': 'ESTADO', 'verbose_name_plural': 'ESTADOS'},
        ),
        migrations.AlterModelOptions(
            name='cat004ciudad',
            options={'managed': False, 'verbose_name': 'CIUDAD', 'verbose_name_plural': 'CIUDADES'},
        ),
    ]
