# Generated by Django 5.0.6 on 2024-07-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Can101Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('primer_nombre', models.TextField(blank=True, max_length=50, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.TextField(blank=True, max_length=50, null=True, verbose_name='Segunndo Nombre')),
                ('primer_apellido', models.TextField(blank=True, max_length=50, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.TextField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido')),
                ('sexo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CANDIDATO',
                'verbose_name_plural': 'CANDIDATOS',
                'db_table': 'can_101_candidato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Can102Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.TextField()),
                ('sector', models.TextField()),
                ('fecha_inicial', models.DateTimeField()),
                ('fecha_final', models.DateTimeField(blank=True, null=True)),
                ('activo', models.IntegerField()),
                ('logro', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'EXPERIENCIA',
                'verbose_name_plural': 'EXPERIENCIAS',
                'db_table': 'can_102_experiencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Can103Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.TextField()),
                ('fecha_inicial', models.DateTimeField()),
                ('fecha_final', models.DateTimeField(blank=True, null=True)),
                ('grado_en', models.TextField(blank=True, null=True)),
                ('titulo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'EDUCACION',
                'db_table': 'can_103_educacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Can104Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
            options={
                'verbose_name': 'SKILL',
                'db_table': 'can_104_skill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Can105SkillCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'can_105_skill_candidato',
                'managed': False,
            },
        ),
    ]
