# Generated by Django 5.0.4 on 2024-07-10 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Can101Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('primer_nombre', models.TextField(blank=True, max_length=50, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.TextField(blank=True, max_length=50, null=True, verbose_name='Segunndo Nombre')),
                ('primer_apellido', models.TextField(blank=True, max_length=50, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.TextField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido')),
                ('sexo', models.TextField(blank=True, null=True)),
                ('ciudad_id_004', models.ForeignKey(blank=True, db_column='ciudad_id_004', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat004ciudad')),
                ('estado_id_001', models.ForeignKey(db_column='estado_id_001', on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'CANDIDATO',
                'verbose_name_plural': 'CANDIDATOS',
                'db_table': 'can_101_candidato',
            },
        ),
        migrations.CreateModel(
            name='Can102Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.TextField()),
                ('sector', models.TextField()),
                ('fecha_inicial', models.DateTimeField()),
                ('fecha_final', models.DateTimeField(blank=True, null=True)),
                ('activo', models.IntegerField()),
                ('logro', models.TextField(blank=True, null=True)),
                ('candidato_id_101', models.ForeignKey(blank=True, db_column='candidato_id_101', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidato.can101candidato')),
                ('estado_id_001', models.ForeignKey(db_column='estado_id_001', on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'EXPERIENCIA',
                'verbose_name_plural': 'EXPERIENCIAS',
                'db_table': 'can_102_experiencia',
            },
        ),
        migrations.CreateModel(
            name='Can103Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.TextField()),
                ('fecha_inicial', models.DateTimeField()),
                ('fecha_final', models.DateTimeField(blank=True, null=True)),
                ('grado_en', models.TextField(blank=True, null=True)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('candidato_id_101', models.ForeignKey(blank=True, db_column='candidato_id_101', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidato.can101candidato')),
                ('estado_id_001', models.ForeignKey(db_column='estado_id_001', on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'EDUCACION',
                'db_table': 'can_103_educacion',
            },
        ),
        migrations.CreateModel(
            name='Can104Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('estado_id_004', models.ForeignKey(db_column='estado_id_004', on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'SKILL',
                'db_table': 'can_104_skill',
            },
        ),
        migrations.CreateModel(
            name='Can105SkillCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato_id_101', models.ForeignKey(db_column='candidato_id_101', on_delete=django.db.models.deletion.DO_NOTHING, to='candidato.can101candidato')),
                ('skill_id_104', models.ForeignKey(db_column='skill_id_104', on_delete=django.db.models.deletion.DO_NOTHING, to='candidato.can104skill')),
            ],
            options={
                'db_table': 'can_105_skill_candidato',
            },
        ),
    ]
