# Generated by Django 5.0.6 on 2024-07-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can101candidato',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=50, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='can101candidato',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=50, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='can101candidato',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='can101candidato',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segunndo Nombre'),
        ),
        migrations.AlterField(
            model_name='can102experiencia',
            name='entidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='can102experiencia',
            name='sector',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='can103educacion',
            name='grado_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='can103educacion',
            name='institucion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='can103educacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='can104skill',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
