# Generated by Django 5.0.6 on 2024-07-31 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_alter_cat001estado_nombre_alter_cat001estado_sigla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Can101Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('primer_nombre', models.CharField(blank=True, max_length=50, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segunndo Nombre')),
                ('primer_apellido', models.CharField(blank=True, max_length=50, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido')),
                ('sexo', models.CharField(blank=True, choices=[('1', 'FEMENINO'), ('2', 'MASCULINO')], max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'CANDIDATO',
                'verbose_name_plural': 'CANDIDATOS',
                'db_table': 'can_101_candidato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Can102Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('fecha_inicial', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True)),
                ('activo', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2)),
                ('logro', models.TextField(blank=True, null=True)),
                ('candidato_id_101', models.ForeignKey(blank=True, db_column='candidato_id_101', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidato.can101candidato')),
                ('estado_id_001', models.ForeignKey(db_column='estado_id_001', on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'EXPERIENCIA',
                'verbose_name_plural': 'EXPERIENCIAS',
                'db_table': 'can_102_experiencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Can103Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=100)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('grado_en', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo', models.CharField(max_length=100)),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('fortaleza_adquiridas', models.TextField(blank=True, null=True)),
                ('candidato_id_101', models.ForeignKey(blank=True, db_column='candidato_id_101', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidato.can101candidato')),
                ('ciudad_id_004', models.ForeignKey(blank=True, db_column='ciudad_id_004', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat004ciudad')),
                ('estado_id_001', models.ForeignKey(db_column='estado_id_001', on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'EDUCACION',
                'db_table': 'can_103_educacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Can104Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado_id_004', models.ForeignKey(db_column='estado_id_004', on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'SKILL',
                'db_table': 'can_104_skill',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Can101CandidatoSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Superior')])),
                ('candidato_id_101', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.can101candidato')),
                ('skill_id_104', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.can104skill')),
            ],
            options={
                'db_table': 'can_101_candidato_skills',
                'managed': True,
            },
        ),
    ]
