# Generated by Django 5.0.6 on 2024-09-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='can101candidato',
            name='user_id',
        ),
    ]
