# Generated by Django 5.0.6 on 2024-07-31 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can101candidatoskill',
            name='candidato_id_101',
            field=models.ForeignKey(db_column='candidato_id_101', on_delete=django.db.models.deletion.CASCADE, to='candidato.can101candidato'),
        ),
        migrations.AlterField(
            model_name='can101candidatoskill',
            name='skill_id_104',
            field=models.ForeignKey(db_column='skill_id_104', on_delete=django.db.models.deletion.CASCADE, to='candidato.can104skill'),
        ),
    ]
