# Generated by Django 5.0.6 on 2024-11-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='can101candidato',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_candidatos/', verbose_name='Imagen de Perfil'),
        ),
    ]
