# Generated by Django 5.0.6 on 2024-08-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_can102experiencia_cargo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='can102experiencia',
            options={'managed': True, 'verbose_name': 'EXPERIENCIA', 'verbose_name_plural': 'EXPERIENCIAS'},
        ),
    ]
