# Generated by Django 5.0.6 on 2024-07-17 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_alter_can101candidato_primer_apellido_and_more'),
        ('common', '0002_alter_cat001estado_nombre_alter_cat001estado_sigla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='can101candidato',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='can101candidato',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='can103educacion',
            name='carrera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='can103educacion',
            name='ciudad_id_004',
            field=models.ForeignKey(blank=True, db_column='ciudad_id_004', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat004ciudad'),
        ),
        migrations.AddField(
            model_name='can103educacion',
            name='fortaleza_adquiridas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='can101candidato',
            name='sexo',
            field=models.CharField(blank=True, choices=[('1', 'FEMENINO'), ('2', 'MASCULINO')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='can102experiencia',
            name='activo',
            field=models.CharField(choices=[('1', 'SI'), ('2', 'NO')], max_length=1),
        ),
        migrations.AlterField(
            model_name='can102experiencia',
            name='fecha_final',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='can102experiencia',
            name='fecha_inicial',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Can105SkillCandidato',
        ),
    ]
