# Generated by Django 5.0.6 on 2024-11-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_can101candidato_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can101candidato',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='candidato/', verbose_name='Imagen de Perfil'),
        ),
    ]
