# Generated by Django 5.0.6 on 2024-12-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0003_alter_can101candidato_imagen_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='can102experiencia',
            name='tipo_estudio',
            field=models.CharField(blank=True, choices=[('1', 'Primaria'), ('2', 'Bachillerato'), ('3', 'Técnico'), ('4', 'Tecnólogo'), ('5', 'Profesional'), ('6', 'Maestría'), ('7', 'Doctorado')], max_length=1, null=True),
        ),
    ]
