# Generated by Django 5.0.6 on 2024-07-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0004_can101candidato_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can102experiencia',
            name='activo',
            field=models.CharField(choices=[('S', 'SI'), ('N', 'NO')], max_length=2),
        ),
    ]
