# Generated by Django 5.0.6 on 2024-08-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0004_alter_can102experiencia_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can102experiencia',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
