# Generated by Django 5.0.6 on 2024-12-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0004_can102experiencia_tipo_estudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='can102experiencia',
            name='tipo_estudio',
        ),
        migrations.AddField(
            model_name='can103educacion',
            name='tipo_estudio',
            field=models.CharField(blank=True, choices=[('1', 'Primaria'), ('2', 'Bachillerato'), ('3', 'Técnico'), ('4', 'Tecnólogo'), ('5', 'Profesional'), ('6', 'Maestría'), ('7', 'Doctorado')], max_length=1, null=True),
        ),
    ]
