# Generated by Django 5.0.6 on 2024-08-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0005_alter_can102experiencia_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can102experiencia',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='can103educacion',
            name='fecha_final',
            field=models.DateField(null=True),
        ),
    ]
