# Generated by Django 5.0.6 on 2024-07-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0005_alter_can102experiencia_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can102experiencia',
            name='activo',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2),
        ),
    ]
