# Generated by Django 5.0.6 on 2025-01-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0005_remove_can102experiencia_tipo_estudio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='can101candidato',
            name='hoja_de_vida',
            field=models.FileField(blank=True, null=True, upload_to='hoja_de_vida/', verbose_name='Hoja de Vida'),
        ),
    ]
