# Generated by Django 5.0.6 on 2025-04-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0006_can101candidato_hoja_de_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='can101candidato',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
