# Generated by Django 5.0.6 on 2024-09-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0006_alter_can102experiencia_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can102experiencia',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='can103educacion',
            name='grado_en',
            field=models.BooleanField(default=False),
        ),
    ]
