# Generated by Django 5.0.6 on 2025-04-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0007_can101candidato_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can101candidato',
            name='hoja_de_vida',
            field=models.FileField(blank=True, null=True, upload_to='media_uploads/hoja_de_vida/', verbose_name='Hoja de Vida'),
        ),
        migrations.AlterField(
            model_name='can101candidato',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='media_uploads/candidato/', verbose_name='Imagen de Perfil'),
        ),
    ]
