# Generated by Django 5.0.6 on 2024-07-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0007_alter_can102experiencia_fecha_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can103educacion',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='can103educacion',
            name='fecha_inicial',
            field=models.DateField(),
        ),
    ]
