# Generated by Django 5.0.6 on 2024-07-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0008_alter_can103educacion_fecha_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can103educacion',
            name='fecha_final',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='can103educacion',
            name='fecha_inicial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='can103educacion',
            name='fortaleza_adquiridas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
