# Generated by Django 5.0.6 on 2025-05-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0008_alter_can101candidato_hoja_de_vida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='can101candidato',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
    ]
