# Generated by Django 5.0.6 on 2025-05-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0009_can101candidato_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can101candidato',
            name='sexo',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('S', 'Sin Especificar'), ('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='can103educacion',
            name='tipo_estudio',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), (1, 'Sin estudios'), (2, 'Primaria'), (3, 'Secundaria/Bachillerato'), (4, 'Técnico'), (5, 'Tecnólogo'), (6, 'Universitario'), (7, 'Postgrado')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='can103educacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
