# Generated by Django 5.0.6 on 2024-07-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0009_alter_can103educacion_fecha_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can103educacion',
            name='carrera',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='can103educacion',
            name='grado_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='can103educacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
