# Generated by Django 5.0.6 on 2024-07-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0010_alter_can103educacion_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can103educacion',
            name='fortaleza_adquiridas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
