# Generated by Django 5.0.6 on 2025-05-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0010_alter_can101candidato_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can102experiencia',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='can103educacion',
            name='tipo_estudio',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('1', 'Sin estudios'), ('2', 'Primaria'), ('3', 'Secundaria/Bachillerato'), ('4', 'Técnico'), ('5', 'Tecnólogo'), ('6', 'Universitario'), ('7', 'Postgrado')], max_length=1, null=True),
        ),
    ]
