# Generated by Django 5.0.6 on 2025-05-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0011_alter_can102experiencia_fecha_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='can103educacion',
            name='certificacion',
            field=models.FileField(blank=True, null=True, upload_to='media_uploads/media_uploads/certificaciones/', verbose_name='Certificación'),
        ),
        migrations.AlterField(
            model_name='can101candidatoskill',
            name='nivel',
            field=models.IntegerField(choices=[('', 'Seleccione una opción...'), (1, 'Básico'), (2, 'Intermedio'), (3, 'Superior')]),
        ),
        migrations.AlterField(
            model_name='can103educacion',
            name='tipo_estudio',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('1', 'Sin estudios'), ('2', 'Primaria'), ('3', 'Secundaria/Bachillerato'), ('4', 'Técnico'), ('5', 'Tecnólogo'), ('6', 'Universitario'), ('7', 'Postgrado'), ('8', 'Diplomado'), ('9', 'Curso')], max_length=2, null=True),
        ),
    ]
