# Generated by Django 5.0.6 on 2024-07-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0011_alter_can103educacion_fortaleza_adquiridas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can103educacion',
            name='fecha_inicial',
            field=models.DateField(null=True),
        ),
    ]
