# Generated by Django 5.0.6 on 2025-05-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0012_can103educacion_certificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='can102experiencia',
            name='modalidad_trabajo',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('R', 'Remoto'), ('P', 'Presencial'), ('H', 'Hibrido')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='can102experiencia',
            name='motivo_salida',
            field=models.IntegerField(blank=True, choices=[('', 'Seleccione una opción...'), (1, 'Renuncia'), (2, 'Justa Causa'), (3, 'Terminación de Contrato')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='can102experiencia',
            name='nombre_jefe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='can102experiencia',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
