# Generated by Django 5.0.6 on 2024-07-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0012_alter_can103educacion_fecha_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can103educacion',
            name='fortaleza_adquiridas',
            field=models.TextField(blank=True),
        ),
    ]
