# Generated by Django 5.0.6 on 2025-05-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0013_can102experiencia_modalidad_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can102experiencia',
            name='motivo_salida',
            field=models.IntegerField(blank=True, choices=[('', 'Seleccione una opción...'), (1, 'Renuncia'), (2, 'Justa Causa'), (3, 'Terminación de Contrato')], null=True),
        ),
    ]
