# Generated by Django 5.0.6 on 2024-07-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0013_alter_can103educacion_fortaleza_adquiridas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can103educacion',
            name='institucion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
