# Generated by Django 5.0.6 on 2025-05-26 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0014_alter_can102experiencia_motivo_salida'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='can101candidato',
            name='perfil',
            field=models.TextField(blank=True, null=True, verbose_name='Perfil del Candidato'),
        ),
        migrations.AddField(
            model_name='can101candidatoskill',
            name='certificado_habilidad',
            field=models.FileField(blank=True, null=True, upload_to='media_uploads/media_uploads/certificados_habilidad/', verbose_name='Certificado de Habilidad'),
        ),
        migrations.AddField(
            model_name='can101candidatoskill',
            name='tipo_habilidad',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('S', 'Suave'), ('D', 'Dura (Técnica)')], max_length=1, null=True, verbose_name='Tipo de Habilidad'),
        ),
        migrations.AlterField(
            model_name='can102experiencia',
            name='motivo_salida',
            field=models.IntegerField(blank=True, choices=[(1, 'Renuncia'), (2, 'Justa Causa'), (3, 'Terminación de Contrato')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Can105RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media_uploads/logos_redes/', verbose_name='Logo de la Red Social')),
                ('url_principal', models.URLField(blank=True, null=True, verbose_name='URL Principal de la Red Social')),
                ('estado_id_001', models.ForeignKey(db_column='estado_id_001', on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'RED SOCIAL',
                'verbose_name_plural': 'REDES SOCIALES',
                'db_table': 'can_105_red_social',
            },
        ),
        migrations.CreateModel(
            name='Can106CandidatoRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL del Perfil')),
                ('candidato_id_101', models.ForeignKey(db_column='candidato_id_101', on_delete=django.db.models.deletion.CASCADE, to='candidato.can101candidato')),
                ('estado_id_001', models.ForeignKey(db_column='estado_id_001', on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat001estado')),
                ('red_social_id_105', models.ForeignKey(db_column='red_social_id_105', on_delete=django.db.models.deletion.CASCADE, to='candidato.can105redsocial')),
            ],
            options={
                'verbose_name': 'CANDIDATO RED',
                'verbose_name_plural': 'CANDIDATOS REDES',
                'db_table': 'can_106_candidato_red',
            },
        ),
    ]
