# Generated by Django 5.0.6 on 2025-05-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0015_can101candidato_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can102experiencia',
            name='motivo_salida',
            field=models.IntegerField(blank=True, choices=[(1, 'Renuncia'), (2, 'Justa Causa'), (3, 'Terminación de Contrato')], max_length=1, null=True),
        ),
    ]
