# Generated by Django 5.0.6 on 2025-05-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0016_alter_can102experiencia_motivo_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can102experiencia',
            name='motivo_salida',
            field=models.IntegerField(blank=True, choices=[(1, 'Renuncia'), (2, 'Justa Causa'), (3, 'Terminación de Contrato')], null=True),
        ),
    ]
