# Generated by Django 5.0.6 on 2025-06-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0017_alter_can102experiencia_motivo_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can101candidato',
            name='hoja_de_vida',
            field=models.FileField(blank=True, null=True, upload_to='media_uploads/media_uploads/hoja_de_vida/', verbose_name='Hoja de Vida'),
        ),
        migrations.AlterField(
            model_name='can101candidato',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='media_uploads/media_uploads/candidato/', verbose_name='Imagen de Perfil'),
        ),
        migrations.AlterField(
            model_name='can105redsocial',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media_uploads/media_uploads/logos_redes/', verbose_name='Logo de la Red Social'),
        ),
    ]
