# Generated by Django 5.0.6 on 2025-07-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0018_alter_can101candidato_hoja_de_vida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can101candidatoskill',
            name='tipo_habilidad',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('S', 'Suave'), ('D', 'Técnica')], max_length=1, null=True, verbose_name='Tipo de Habilidad'),
        ),
    ]
