# Generated by Django 5.0.6 on 2025-07-02 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0019_alter_can101candidatoskill_tipo_habilidad'),
        ('vacante', '0031_cli055profesionestudio_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='can103educacion',
            name='profesion_estudio',
            field=models.ForeignKey(blank=True, db_column='profesion_estudio_id_055', null=True, on_delete=django.db.models.deletion.CASCADE, to='vacante.cli055profesionestudio', verbose_name='Profesión/Estudio'),
        ),
    ]
