# Generated by Django 5.0.6 on 2025-07-04 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0020_can103educacion_profesion_estudio'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Can107GrupoSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Grupo de Skill')),
                ('estado_id_001', models.ForeignKey(db_column='estado_id_001', on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'GRUPO SKILL',
                'verbose_name_plural': 'GRUPOS SKILL',
                'db_table': 'can_107_grupo_skill',
            },
        ),
        migrations.AddField(
            model_name='can104skill',
            name='grupo',
            field=models.ForeignKey(blank=True, db_column='grupo_id_107', null=True, on_delete=django.db.models.deletion.CASCADE, to='candidato.can107gruposkill', verbose_name='Grupo de Skill'),
        ),
    ]
