# Generated by Django 5.0.6 on 2025-08-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0021_can107gruposkill_can104skill_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='can101candidato',
            name='aspiracion_salarial',
            field=models.IntegerField(blank=True, null=True, verbose_name='Aspiración Salarial'),
        ),
        migrations.AddField(
            model_name='can101candidato',
            name='fit_cultural',
            field=models.JSONField(blank=True, help_text='Fit cultural en formato JSON', null=True, verbose_name='Fit Cultural'),
        ),
        migrations.AddField(
            model_name='can101candidato',
            name='motivadores',
            field=models.JSONField(blank=True, help_text='Motivadores en formato JSON', null=True, verbose_name='Motivadores'),
        ),
    ]
