# Generated by Django 5.0.6 on 2026-01-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0022_can101candidato_aspiracion_salarial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='can101candidato',
            name='video_perfil',
            field=models.FileField(blank=True, help_text='Sube un video desde tu dispositivo móvil o web', null=True, upload_to='media_uploads/media_uploads/videos_candidato/', verbose_name='Video de Perfil'),
        ),
    ]
