# Generated by Django 5.0.6 on 2026-02-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0023_can101candidato_video_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='can103educacion',
            name='estado_estudios',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('G', 'Graduado'), ('C', 'En curso'), ('A', 'Aplazado')], max_length=1, null=True),
        ),
    ]
