# Generated by Django 5.0.6 on 2026-02-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0024_can103educacion_estado_estudios'),
    ]

    operations = [
        migrations.AddField(
            model_name='can102experiencia',
            name='experiencia_laboral',
            field=models.BooleanField(default=False),
        ),
    ]
