# Generated by Django 5.0.6 on 2026-02-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0025_can102experiencia_experiencia_laboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='can102experiencia',
            name='certificado_laboral',
            field=models.FileField(blank=True, null=True, upload_to='media_uploads/media_uploads/certificados_laborales/', verbose_name='Certificado de Laboral'),
        ),
    ]
