# Generated by Django 5.0.6 on 2026-02-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0026_can102experiencia_certificado_laboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='can101candidato',
            name='idiomas',
            field=models.JSONField(blank=True, help_text='Idiomas en formato JSON', null=True, verbose_name='Idiomas'),
        ),
        migrations.AlterField(
            model_name='can102experiencia',
            name='motivo_salida',
            field=models.IntegerField(blank=True, choices=[('', 'Seleccione una opción...'), (1, 'Renuncia'), (2, 'Justa Causa'), (3, 'Terminación de Contrato')], null=True),
        ),
    ]
