# Generated by Django 5.0.6 on 2026-03-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0027_can101candidato_idiomas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='can102experiencia',
            name='funciones_desempenadas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
