# Generated by Django 5.0.6 on 2024-12-23 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('vacante', '0014_delete_cli057asignacionentrevista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cli057AsignacionEntrevista',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrevista', models.DateField()),
                ('hora_entrevista', models.TimeField()),
                ('tipo_entrevista', models.CharField(choices=[('V', 'Virtual'), ('P', 'Presencial')], max_length=1)),
                ('lugar_enlace', models.CharField(max_length=255)),
                ('estado_asignacion', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Apto'), (3, 'No Apto'), (4, 'Seleccionado'), (5, 'Cancelado')], default=1)),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha_gestion', models.DateField(auto_now=True)),
                ('asignacion_vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_entrevista', to='vacante.cli056aplicacionvacante')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat001estado')),
                ('usuario_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevistas_por_realizar', to=settings.AUTH_USER_MODEL)),
                ('usuario_asigno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevistas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ASIGNACIÓN DE ENTREVISTA',
                'verbose_name_plural': 'ASIGNACIONES DE ENTREVISTAS',
                'db_table': 'cli_057_asignacion_entrevista',
            },
        ),
    ]
