# Generated by Django 5.0.6 on 2024-12-24 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0001_initial'),
        ('reclutado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli057asignacionentrevista',
            name='asignacion_vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_entrevista', to='reclutado.cli056aplicacionvacante'),
        ),
    ]
