# Generated by Django 5.0.6 on 2025-12-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0002_alter_cli057asignacionentrevista_asignacion_vacante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli057asignacionentrevista',
            name='resultado_entrevista',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
