# Generated by Django 5.0.6 on 2026-02-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0003_cli057asignacionentrevista_resultado_entrevista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli057asignacionentrevista',
            name='estado_asignacion',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Apto'), (3, 'No Apto'), (4, 'Seleccionado'), (5, 'Cancelado'), (6, 'Rechazado'), (7, 'No Asistió')], default=1),
        ),
    ]
