# Generated by Django 5.0.6 on 2024-07-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cli051cliente_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli051cliente',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/logos/'),
        ),
        migrations.AddField(
            model_name='cli051cliente',
            name='perfil_empresarial',
            field=models.TextField(blank=True),
        ),
    ]
