# Generated by Django 5.0.6 on 2025-02-21 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cli058pregunta_cli059cuestionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli051cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('1', 'empresa'), ('2', 'headhunter'), ('3', 'cliente_empresa')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='Cli064AsignacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('id_cliente_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_asignado', to='cliente.cli051cliente')),
                ('id_cliente_maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_maestro', to='cliente.cli051cliente')),
            ],
            options={
                'verbose_name': 'ASIGNACION_CLIENTE',
                'verbose_name_plural': 'ASIGNACIONES_CLIENTES',
                'db_table': 'cli_064_asignacion_cliente',
                'unique_together': {('id_cliente_maestro', 'id_cliente_asignado')},
            },
        ),
    ]
