# Generated by Django 5.0.6 on 2024-07-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cli051cliente_logo_cli051cliente_perfil_empresarial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli051cliente',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cliente'),
        ),
    ]
