# Generated by Django 5.0.6 on 2025-02-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cli051cliente_tipo_cliente_cli064asignacioncliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli064asignacioncliente',
            name='tipo_asignacion',
            field=models.CharField(choices=[('1', 'Asignación Cliente'), ('2', 'Asignación Headhunter')], default='1', max_length=1),
        ),
    ]
