# Generated by Django 5.0.6 on 2025-02-26 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_cli064asignacioncliente_tipo_asignacion'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli051cliente',
            name='cantidad_colaboradores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cli051cliente',
            name='periodicidad_pago',
            field=models.CharField(blank=True, choices=[('', 'Sin Definir'), ('1', 'Semanal'), ('2', 'Quincenal'), ('3', 'Mensual')], default='1', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cli051cliente',
            name='referencias_laborales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cli064asignacioncliente',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat001estado'),
        ),
        migrations.AlterField(
            model_name='cli051cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('1', 'Empresa'), ('2', 'Headhunter'), ('3', 'Cliente_empresa')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='Cli065ActividadEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'ACTIVIDAD_ECONOMICA',
                'verbose_name_plural': 'ACTIVIDADES_ECONOMICAS',
                'db_table': 'cli_065_actividad_economica',
            },
        ),
        migrations.AddField(
            model_name='cli051cliente',
            name='actividad_economica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cli065actividadeconomica'),
        ),
    ]
