# Generated by Django 5.0.6 on 2025-02-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_cli051cliente_cantidad_colaboradores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli051cliente',
            name='contacto_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cli051cliente',
            name='direccion_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cli051cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('1', 'Empresa'), ('2', 'Headhunter'), ('3', 'Cliente Headhunter')], default='1', max_length=1),
        ),
    ]
