# Generated by Django 5.0.6 on 2025-02-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_cli051cliente_contacto_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli051cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('1', 'Cliente Standard'), ('2', 'Cliente Headhunter'), ('3', 'Cliente Asignado Headhunter')], default='1', max_length=1),
        ),
    ]
