# Generated by Django 5.0.6 on 2025-03-03 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_cli051cliente_tipo_cliente'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cli066PruebasPsicologicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'PRUEBA_PSICOLOGICA',
                'verbose_name_plural': 'PRUEBAS_PSICOLOGICAS',
                'db_table': 'cli_066_pruebas_psicologicas',
            },
        ),
        migrations.CreateModel(
            name='Cli067PoliticasInternas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'POLITICA_INTERNA',
                'verbose_name_plural': 'POLITICAS_INTERNAS',
                'db_table': 'cli_067_politicas_internas',
            },
        ),
        migrations.CreateModel(
            name='Cli051ClientePruebas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cli051cliente')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='common.cat001estado')),
                ('prueba_psicologica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cli066pruebaspsicologicas')),
            ],
            options={
                'db_table': 'cli_051_cliente_pruebas',
                'unique_together': {('cliente', 'prueba_psicologica')},
            },
        ),
        migrations.CreateModel(
            name='Cli051ClientePoliticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cli051cliente')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='common.cat001estado')),
                ('politica_interna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cli067politicasinternas')),
            ],
            options={
                'db_table': 'cli_051_cliente_politicas',
                'unique_together': {('cliente', 'politica_interna')},
            },
        ),
    ]
