# Generated by Django 5.0.6 on 2025-03-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_cli066pruebaspsicologicas_cli067politicasinternas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli066pruebaspsicologicas',
            name='cargos_recomendados',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cli066pruebaspsicologicas',
            name='uso',
            field=models.TextField(blank=True),
        ),
    ]
