# Generated by Django 5.0.6 on 2025-03-06 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_cli066pruebaspsicologicas_cargos_recomendados_and_more'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cli068Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=100)),
                ('fecha_creado', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cli051cliente')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'CARGO',
                'verbose_name_plural': 'CARGOS',
                'db_table': 'cli_068_cargos',
            },
        ),
        migrations.CreateModel(
            name='Cli069Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creado', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cli051cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'REQUISITO',
                'verbose_name_plural': 'REQUISITOS',
                'db_table': 'cli_069_requisito',
            },
        ),
        migrations.CreateModel(
            name='Cli070AsignacionRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cli068cargo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cat001estado')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cli069requisito')),
            ],
            options={
                'verbose_name': 'ASIGNACION_REQUISITO',
                'verbose_name_plural': 'ASIGNACIONES_REQUISITOS',
                'db_table': 'cli_070_asignacion_requisito',
                'unique_together': {('cargo', 'requisito')},
            },
        ),
        migrations.CreateModel(
            name='Cli071AsignacionPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cli068cargo')),
                ('cliente_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cli051clientepruebas')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'ASIGNACION_PRUEBA',
                'verbose_name_plural': 'ASIGNACIONES_PRUEBAS',
                'db_table': 'cli_071_asignacion_prueba',
                'unique_together': {('cliente_prueba', 'cargo')},
            },
        ),
    ]
