# Generated by Django 5.0.6 on 2025-03-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_cli068cargo_cli069requisito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli051cliente',
            name='periodicidad_pago',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción...'), ('', 'Sin Definir'), ('1', 'Semanal'), ('2', 'Quincenal'), ('3', 'Mensual')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cli051cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('', 'Seleccione una opción...'), ('1', 'Cliente Standard'), ('2', 'Cliente Headhunter'), ('3', 'Cliente Asignado Headhunter')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='cli061asignacioncandidatocuestionario',
            name='estado',
            field=models.CharField(choices=[('', 'Seleccione una opción...'), ('p', 'Pendiente'), ('r', 'Realizado')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='cli064asignacioncliente',
            name='tipo_asignacion',
            field=models.CharField(choices=[('', 'Seleccione una opción...'), ('1', 'Asignación Cliente'), ('2', 'Asignación Headhunter')], default='1', max_length=1),
        ),
    ]
