# Generated by Django 5.0.6 on 2025-04-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_alter_cli051cliente_periodicidad_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli051cliente',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media_uploads/cliente/'),
        ),
    ]
