# Generated by Django 5.0.6 on 2025-07-11 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_alter_cli051cliente_logo'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cli076GrupoFitCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Grupo de Fit Cultural')),
                ('estado', models.ForeignKey(db_column='estado_id_001', on_delete=django.db.models.deletion.CASCADE, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'GRUPO FIT CULTURAL',
                'verbose_name_plural': 'GRUPOS FIT CULTURAL',
                'db_table': 'cli_076_grupo_fit_cultural',
            },
        ),
        migrations.CreateModel(
            name='Cli077FitCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.ForeignKey(db_column='estado_id_004', on_delete=django.db.models.deletion.CASCADE, to='common.cat001estado')),
                ('grupo', models.ForeignKey(blank=True, db_column='grupo_id_076', null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cli076grupofitcultural', verbose_name='Grupo de Fit Cultural')),
            ],
            options={
                'verbose_name': 'FIT CULTURAL',
                'verbose_name_plural': 'FITS CULTURALES',
                'db_table': 'cli_077_fit_cultural',
            },
        ),
    ]
