# Generated by Django 5.0.6 on 2025-07-11 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0015_cli076grupofitcultural_cli077fitcultural'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cli078MotivadoresCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(db_column='estado_id_004', on_delete=django.db.models.deletion.CASCADE, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'MOTIVADOR CANDIDATO',
                'verbose_name_plural': 'MOTIVADORES CANDIDATO',
                'db_table': 'cli_078_motivadores_candidato',
            },
        ),
    ]
