# Generated by Django 5.0.6 on 2025-10-16 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0016_cli078motivadorescandidato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cli051cliente',
            name='cantidad_colaboradores',
        ),
        migrations.RemoveField(
            model_name='cli051cliente',
            name='referencias_laborales',
        ),
    ]
