# Generated by Django 5.0.6 on 2025-10-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0017_remove_cli051cliente_cantidad_colaboradores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli051cliente',
            name='cantidad_colaboradores',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
