# Generated by Django 5.0.6 on 2025-10-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0018_cli051cliente_cantidad_colaboradores'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli068cargo',
            name='referencias_laborales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
