# Generated by Django 5.0.6 on 2026-02-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0019_cli068cargo_referencias_laborales'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli077fitcultural',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
