# Generated by Django 5.0.6 on 2026-02-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0020_cli077fitcultural_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli051clientepoliticas',
            name='respuestas_politica',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
