# Generated by Django 5.0.6 on 2026-02-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0021_cli051clientepoliticas_respuestas_politica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cli051clientepoliticas',
            name='respuestas_politica',
        ),
        migrations.AddField(
            model_name='cli067politicasinternas',
            name='respuestas_politica',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
