# Generated by Django 5.0.6 on 2024-07-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cli051cliente',
            options={'verbose_name': 'CLIENTE', 'verbose_name_plural': 'CLIENTES'},
        ),
    ]
