# Generated by Django 5.0.6 on 2024-07-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli051cliente',
            name='contacto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cli051cliente',
            name='razon_social',
            field=models.CharField(max_length=100),
        ),
    ]
