# Generated by Django 5.0.6 on 2024-07-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cli051cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cli051cliente',
            options={'managed': False, 'verbose_name': 'CLIENTE', 'verbose_name_plural': 'CLIENTES'},
        ),
    ]
