# Generated by Django 5.0.6 on 2024-07-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cli051cliente_options'),
    ]

    operations = [
    ]
