# Generated by Django 5.0.6 on 2024-09-27 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenautorizacion',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 28, 17, 14, 18, 354907, tzinfo=datetime.timezone.utc)),
        ),
    ]
