# Generated by Django 5.0.6 on 2024-09-16 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_grupo_permiso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='permiso',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tokenautorizacion',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 17, 17, 49, 22, 890848, tzinfo=datetime.timezone.utc)),
        ),
    ]
