# Generated by Django 5.0.6 on 2024-09-30 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_tokenautorizacion_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenautorizacion',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 17, 3, 46, 471888, tzinfo=datetime.timezone.utc)),
        ),
    ]
