# Generated by Django 5.0.6 on 2024-10-02 19:53

import applications.usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_tokenautorizacion_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenautorizacion',
            name='fecha_expiracion',
            field=models.DateTimeField(default=applications.usuarios.models.calcular_fecha_expiracion),
        ),
    ]
