# Generated by Django 5.0.6 on 2024-09-16 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_grupo_permiso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenautorizacion',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 17, 17, 52, 1, 367546, tzinfo=datetime.timezone.utc)),
        ),
    ]
