# Generated by Django 5.0.6 on 2024-10-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_tokenautorizacion_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariobase',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='usuariobase',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='usuariobase',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='usuariobase',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
