# Generated by Django 5.0.6 on 2025-04-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuariobase_primer_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariobase',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuario/', verbose_name='Imagen de Perfil Usuario'),
        ),
    ]
