# Generated by Django 5.0.6 on 2024-09-16 19:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_tokenautorizacion_fecha_expiracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'PERMISO',
                'verbose_name_plural': 'PERMISOS',
                'db_table': 'permiso',
            },
        ),
        migrations.AlterField(
            model_name='tokenautorizacion',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 17, 19, 24, 54, 477732, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='usuarios.permiso', verbose_name='Permiso'),
        ),
    ]
