# Generated by Django 5.0.6 on 2024-09-16 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_permiso_alter_tokenautorizacion_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tokenautorizacion',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 17, 19, 31, 41, 326389, tzinfo=datetime.timezone.utc)),
        ),
    ]
