# Generated by Django 5.0.6 on 2024-09-16 21:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_grupo_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='permiso',
        ),
        migrations.AlterField(
            model_name='permiso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tokenautorizacion',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 17, 21, 18, 4, 838711, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='GrupoPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_permisos', to='usuarios.grupo')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_permisos', to='usuarios.permiso')),
            ],
            options={
                'verbose_name': 'ASIGNACIÓN DE PERMISO A GRUPO',
                'verbose_name_plural': 'ASIGNACIONES DE PERMISOS A GRUPOS',
                'db_table': 'grupo_permiso',
                'unique_together': {('grupo', 'permiso')},
            },
        ),
    ]
