# Generated by Django 5.0.6 on 2024-09-18 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_grupo_permiso_alter_permiso_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenautorizacion',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 14, 51, 3, 127308, tzinfo=datetime.timezone.utc)),
        ),
    ]
