# Generated by Django 5.0.6 on 2024-09-18 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_tokenautorizacion_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenautorizacion',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 15, 8, 33, 185374, tzinfo=datetime.timezone.utc)),
        ),
    ]
