# Generated by Django 5.0.6 on 2024-09-18 15:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_remove_can101candidato_user_id'),
        ('usuarios', '0011_alter_tokenautorizacion_fecha_expiracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariobase',
            name='candidato_id_101',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='candidato.can101candidato'),
        ),
        migrations.AlterField(
            model_name='tokenautorizacion',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 15, 34, 33, 993204, tzinfo=datetime.timezone.utc)),
        ),
    ]
