# Generated by Django 5.0.6 on 2024-09-18 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_usuariobase_candidato_id_101_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenautorizacion',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 15, 41, 3, 446915, tzinfo=datetime.timezone.utc)),
        ),
    ]
