# Generated by Django 5.0.6 on 2024-12-24 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidato', '0005_remove_can102experiencia_tipo_estudio_and_more'),
        ('vacante', '0014_delete_cli057asignacionentrevista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cli056AplicacionVacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado_aplicacion', models.IntegerField(choices=[(1, 'Aplicado'), (2, 'Entrevista Programada'), (3, 'Entrevista Aprobada'), (4, 'Entrevista No Aprobada'), (5, 'Prueba Programada'), (6, 'Prueba Superada'), (7, 'Prueba No Superada'), (8, 'Seleccionado'), (9, 'Finalizada'), (10, 'Cancelada'), (11, 'Desiste'), (12, 'No Apto')], default=1)),
                ('candidato_101', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='candidato.can101candidato')),
                ('vacante_id_052', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='vacante.cli052vacante')),
            ],
            options={
                'verbose_name': 'APLICACIÓN A VACANTE',
                'verbose_name_plural': 'APLICACIONES A VACANTES',
                'db_table': 'cli_056_aplicacion_vacante',
                'unique_together': {('candidato_101', 'vacante_id_052')},
            },
        ),
        migrations.CreateModel(
            name='Cli063AplicacionVacanteHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(choices=[(1, 'Aplicado'), (2, 'Entrevista Programada'), (3, 'Entrevista Aprobada'), (4, 'Entrevista No Aprobada'), (5, 'Prueba Programada'), (6, 'Prueba Superada'), (7, 'Prueba No Superada'), (8, 'Seleccionado'), (9, 'Finalizada'), (10, 'Cancelada'), (11, 'Desiste'), (12, 'No Apto')])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('aplicacion_vacante_056', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='reclutado.cli056aplicacionvacante')),
                ('usuario_id_genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Aplicación a Vacante',
                'verbose_name_plural': 'Historiales de Aplicaciones a Vacantes',
                'db_table': 'cli_063_aplicacion_vacante_historial',
            },
        ),
    ]
