# Generated by Django 5.0.6 on 2025-04-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('reclutado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli056aplicacionvacante',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones_vacante', to='common.cat001estado'),
        ),
    ]
