# Generated by Django 5.0.6 on 2025-08-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutado', '0002_cli056aplicacionvacante_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli056aplicacionvacante',
            name='preguntas_reclutamiento',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
