# Generated by Django 5.0.6 on 2025-08-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutado', '0003_cli056aplicacionvacante_preguntas_reclutamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli056aplicacionvacante',
            name='json_match',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
