# Generated by Django 5.0.6 on 2025-12-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutado', '0004_cli056aplicacionvacante_json_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli056aplicacionvacante',
            name='estado_reclutamiento',
            field=models.IntegerField(choices=[('', 'Seleccione una opción...'), (1, 'Recibido'), (2, 'Seleccionado'), (3, 'Finalizalista'), (4, 'Descartado')], default=1),
        ),
    ]
