# Generated by Django 5.0.6 on 2025-12-17 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutado', '0005_cli056aplicacionvacante_estado_reclutamiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cli056aplicacionvacante',
            name='usuario_reclutador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones_reclutador', to=settings.AUTH_USER_MODEL),
        ),
    ]
