# Generated by Django 5.0.6 on 2025-12-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutado', '0006_cli056aplicacionvacante_usuario_reclutador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli056aplicacionvacante',
            name='registro_reclutamiento',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
