# Generated by Django 5.0.6 on 2026-02-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutado', '0007_cli056aplicacionvacante_registro_reclutamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli056aplicacionvacante',
            name='json_match_inicial',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cli056aplicacionvacante',
            name='estado_aplicacion',
            field=models.IntegerField(choices=[(1, 'Aplicado'), (2, 'Entrevista Programada'), (3, 'Entrevista Aprobada'), (4, 'Entrevista No Aprobada'), (5, 'Prueba Programada'), (6, 'Prueba Superada'), (7, 'Prueba No Superada'), (8, 'Seleccionado'), (9, 'Finalizada'), (10, 'Cancelada'), (11, 'Desiste'), (12, 'No Apto'), (13, 'Seleccionado por Headhunter')], default=1),
        ),
        migrations.AlterField(
            model_name='cli063aplicacionvacantehistorial',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Aplicado'), (2, 'Entrevista Programada'), (3, 'Entrevista Aprobada'), (4, 'Entrevista No Aprobada'), (5, 'Prueba Programada'), (6, 'Prueba Superada'), (7, 'Prueba No Superada'), (8, 'Seleccionado'), (9, 'Finalizada'), (10, 'Cancelada'), (11, 'Desiste'), (12, 'No Apto'), (13, 'Seleccionado por Headhunter')]),
        ),
    ]
