# Generated by Django 5.0.6 on 2026-02-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutado', '0008_cli056aplicacionvacante_json_match_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli056aplicacionvacante',
            name='json_politicas_internas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cli056aplicacionvacante',
            name='json_pruebas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cli056aplicacionvacante',
            name='json_requisitos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
