# Generated by Django 5.0.6 on 2026-02-17 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0020_cli077fitcultural_descripcion'),
        ('common', '0001_initial'),
        ('reclutado', '0009_cli056aplicacionvacante_json_politicas_internas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cli056aplicacionvacante',
            name='json_politicas_internas',
        ),
        migrations.RemoveField(
            model_name='cli056aplicacionvacante',
            name='json_pruebas',
        ),
        migrations.RemoveField(
            model_name='cli056aplicacionvacante',
            name='json_requisitos',
        ),
        migrations.CreateModel(
            name='Cli080DocumentoFirmadoAplicacionVacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_firmada', models.ImageField(blank=True, null=True, upload_to='media_uploads/firmas/', verbose_name='Imagen Firma')),
                ('ip_firmante', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_firma_hora_ip', models.DateTimeField(auto_now_add=True)),
                ('aplicacion_vacante_056', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_firmar', to='reclutado.cli056aplicacionvacante')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_firmados', to='common.cat001estado')),
                ('usuario_firmante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_firmados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DOCUMENTO FIRMAR APLICACIÓN A VACANTE',
                'verbose_name_plural': 'DOCUMENTOS FIRMAR APLICACIONES A VACANTES',
                'db_table': 'cli_080_documentos_firmar_aplicacion_vacante',
            },
        ),
        migrations.CreateModel(
            name='Cli079RequisitosCargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_requisito', models.FileField(blank=True, null=True, upload_to='media_uploads/requisitos/', verbose_name='Archivo Requisito')),
                ('fecha_cargado', models.DateTimeField(auto_now_add=True)),
                ('aplicacion_vacante_056', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_cargados', to='reclutado.cli056aplicacionvacante')),
                ('asignacion_requisito_070', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_cargados', to='cliente.cli070asignacionrequisito')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_cargados', to='common.cat001estado')),
                ('usuario_cargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_cargados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'REQUISITO CARGADO',
                'verbose_name_plural': 'REQUISITOS CARGADOS',
                'db_table': 'cli_079_requisitos_cargado',
                'unique_together': {('aplicacion_vacante_056', 'asignacion_requisito_070')},
            },
        ),
    ]
