# Generated by Django 5.0.6 on 2026-02-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutado', '0010_remove_cli056aplicacionvacante_json_politicas_internas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli056aplicacionvacante',
            name='json_politicas_internas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
