# Generated by Django 5.0.6 on 2026-02-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutado', '0011_cli056aplicacionvacante_json_politicas_internas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli080documentofirmadoaplicacionvacante',
            name='documento_firmado',
            field=models.FileField(blank=True, null=True, upload_to='media_uploads/documentos_firmados/', verbose_name='Documento Firmado'),
        ),
    ]
