# Generated by Django 5.0.6 on 2026-02-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutado', '0012_cli080documentofirmadoaplicacionvacante_documento_firmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli080documentofirmadoaplicacionvacante',
            name='codigo_unico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
