# Generated by Django 5.0.6 on 2026-02-18 21:55

import applications.reclutado.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutado', '0013_cli080documentofirmadoaplicacionvacante_codigo_unico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cli081TokenGeneradoDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(default=applications.reclutado.models.calcular_fecha_expiracion)),
                ('aplicacion_vacante_056', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacion_vacante_token_generado', to='reclutado.cli056aplicacionvacante')),
            ],
            options={
                'verbose_name': 'TOKEN GENERADO DOCUMENTOS',
                'verbose_name_plural': 'TOKEN GENERADOS DOCUMENTOS',
                'db_table': 'cli_081_token_generado_documentos',
                'unique_together': {('aplicacion_vacante_056', 'token')},
            },
        ),
    ]
