# Generated by Django 5.0.6 on 2026-02-19 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('reclutado', '0014_cli081tokengeneradodocumentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cli081tokengeneradodocumentos',
            name='estado',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_generado_documentos', to='common.cat001estado'),
        ),
        migrations.AddField(
            model_name='cli081tokengeneradodocumentos',
            name='usuario_generador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_generado_documentos', to=settings.AUTH_USER_MODEL),
        ),
    ]
