# Generated by Django 5.0.6 on 2026-02-22 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('reclutado', '0015_cli081tokengeneradodocumentos_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli081tokengeneradodocumentos',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_generado_documentos', to='common.cat001estado'),
        ),
        migrations.AlterField(
            model_name='cli081tokengeneradodocumentos',
            name='usuario_generador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_generado_documentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cli082PruebaCargada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prueba_cargada', models.FileField(blank=True, null=True, upload_to='media_uploads/pruebas/', verbose_name='Prueba Cargada')),
                ('fecha_cargada', models.DateTimeField(auto_now_add=True)),
                ('aplicacion_vacante_056', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacion_vacante_prueba_cargada', to='reclutado.cli056aplicacionvacante')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prueba_cargada', to='common.cat001estado')),
                ('usuario_cargada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prueba_cargada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PRUEBA CARGADA',
                'verbose_name_plural': 'PRUEBAS CARGADAS',
                'db_table': 'cli_082_prueba_cargada',
            },
        ),
    ]
