# Generated by Django 5.0.6

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('reclutado', '0016_alter_cli081tokengeneradodocumentos_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cli083ConfiabilidadRiesgoCargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_cargado', models.FileField(blank=True, null=True, upload_to='media_uploads/confiabilidad_riesgo/', verbose_name='Documento Confiabilidad/Riesgo')),
                ('fecha_cargado', models.DateTimeField(auto_now_add=True)),
                ('aplicacion_vacante_056', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confiabilidad_riesgo_cargados', to='reclutado.cli056aplicacionvacante')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confiabilidad_riesgo_cargados', to='common.cat001estado')),
                ('usuario_cargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confiabilidad_riesgo_cargados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CONFIABILIDAD RIESGO CARGADO',
                'verbose_name_plural': 'CONFIABILIDAD RIESGO CARGADOS',
                'db_table': 'cli_083_confiabilidad_riesgo_cargado',
            },
        ),
    ]
