# Generated by Django 5.0.6 on 2026-03-19 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_cat005asignacionqr_options_and_more'),
        ('reclutado', '0017_cli083confiabilidadriesgocargado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cli084AsignacionRegistroReclutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('asignacion_qr_005', models.ForeignKey(db_column='asignacion_qr_005', on_delete=django.db.models.deletion.CASCADE, related_name='registros_reclutados', to='common.cat005asignacionqr')),
                ('estado', models.ForeignKey(db_column='estado_id_001', on_delete=django.db.models.deletion.DO_NOTHING, related_name='asignaciones_registro_reclutado', to='common.cat001estado')),
                ('usuario_registrado', models.ForeignKey(db_column='usuario_registrado', on_delete=django.db.models.deletion.CASCADE, related_name='registros_qr_reclutador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ASIGNACIÓN REGISTRO RECLUTADO',
                'verbose_name_plural': 'ASIGNACIONES REGISTRO RECLUTADO',
                'db_table': 'cli_084_asignacion_registro_reclutado',
            },
        ),
    ]
