# Generated by Django 5.0.6 on 2026-04-28 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0028_can102experiencia_funciones_desempenadas'),
        ('reclutado', '0020_cli087_fecha_actualizacion_usuario_actualizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli056aplicacionvacante',
            name='estado_aplicacion',
            field=models.IntegerField(choices=[(1, 'Aplicado'), (2, 'Entrevista Programada'), (3, 'Entrevista Aprobada'), (4, 'Entrevista No Aprobada'), (5, 'Acciones Desicivas Programadas'), (6, 'Acciones Desicivas Aprobadas'), (7, 'Acciones Desicivas No Aprobadas'), (8, 'Seleccionado'), (9, 'Finalizada'), (10, 'Cancelada'), (11, 'Desiste'), (12, 'No Apto'), (13, 'En espera por respuesta de contratación'), (14, 'No contratado'), (15, 'Contratado')], default=1),
        ),
        migrations.AlterField(
            model_name='cli056aplicacionvacante',
            name='estado_reclutamiento',
            field=models.IntegerField(choices=[('', 'Seleccione una opción...'), (1, 'Aspirantes'), (2, 'Precalficados por CV'), (3, 'Aprobados para Entrevista'), (4, 'No aprobados por CV')], default=1),
        ),
        migrations.AlterField(
            model_name='cli063aplicacionvacantehistorial',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Aplicado'), (2, 'Entrevista Programada'), (3, 'Entrevista Aprobada'), (4, 'Entrevista No Aprobada'), (5, 'Acciones Desicivas Programadas'), (6, 'Acciones Desicivas Aprobadas'), (7, 'Acciones Desicivas No Aprobadas'), (8, 'Seleccionado'), (9, 'Finalizada'), (10, 'Cancelada'), (11, 'Desiste'), (12, 'No Apto'), (13, 'En espera por respuesta de contratación'), (14, 'No contratado'), (15, 'Contratado')]),
        ),
        migrations.CreateModel(
            name='Cli088ReferenciasLaborales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato_trabajo_en_empresa', models.BooleanField(blank=True, null=True)),
                ('periodo_empleo_coincide', models.BooleanField(blank=True, null=True)),
                ('periodo_empleo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_empleo_fin', models.DateField(blank=True, null=True)),
                ('cargo_mencionado', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo_mencionado_verificado', models.BooleanField(blank=True, null=True)),
                ('jefe_mencionado', models.CharField(blank=True, max_length=255, null=True)),
                ('jefe_mencionado_verificado', models.BooleanField(blank=True, null=True)),
                ('volveria_a_contratar', models.BooleanField(blank=True, null=True)),
                ('cargo_validador', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_validacion', models.DateField(blank=True, null=True)),
                ('comentario_adicional', models.TextField(blank=True, null=True)),
                ('firma_digital', models.ImageField(blank=True, null=True, upload_to='media_uploads/firmas_referencias_laborales/')),
                ('firmado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aplicacion_vacante_056', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_laborales', to='reclutado.cli056aplicacionvacante')),
                ('experiencia_candidato_102', models.ForeignKey(blank=True, help_text='Experiencia laboral del candidato (can_102_experiencia) referenciada por esta validación.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validaciones_referencias', to='candidato.can102experiencia')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias_laborales_validadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'REFERENCIAS LABORALES (VALIDACIÓN)',
                'verbose_name_plural': 'REFERENCIAS LABORALES (VALIDACIONES)',
                'db_table': 'cli_088_referencias_laborales',
            },
        ),
    ]
