# Generated by Django 5.0.6 on 2026-04-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclutado', '0021_alter_cli056aplicacionvacante_estado_aplicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cli088referenciaslaborales',
            name='cargo_mencionado',
        ),
        migrations.RemoveField(
            model_name='cli088referenciaslaborales',
            name='cargo_validador',
        ),
        migrations.RemoveField(
            model_name='cli088referenciaslaborales',
            name='comentario_adicional',
        ),
        migrations.RemoveField(
            model_name='cli088referenciaslaborales',
            name='fecha_validacion',
        ),
        migrations.RemoveField(
            model_name='cli088referenciaslaborales',
            name='firma_digital',
        ),
        migrations.RemoveField(
            model_name='cli088referenciaslaborales',
            name='firmado_por',
        ),
        migrations.RemoveField(
            model_name='cli088referenciaslaborales',
            name='jefe_mencionado',
        ),
        migrations.RemoveField(
            model_name='cli088referenciaslaborales',
            name='periodo_empleo_fin',
        ),
        migrations.RemoveField(
            model_name='cli088referenciaslaborales',
            name='periodo_empleo_inicio',
        ),
    ]
