# Generated by Django 5.0.6 on 2026-04-28 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutado', '0022_remove_cli088referenciaslaborales_cargo_mencionado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cli088referenciaslaborales',
            name='aplicacion_vacante_056',
        ),
        migrations.AddField(
            model_name='cli088referenciaslaborales',
            name='reporte_accion_decisiva_087',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='referencias_laborales', to='reclutado.cli087reporteacciondecisivareclutado'),
            preserve_default=False,
        ),
    ]
