# Generated by Django 5.0.6 on 2026-04-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutado', '0023_remove_cli088referenciaslaborales_aplicacion_vacante_056_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cli088referenciaslaborales',
            name='comentario_adicional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cli088referenciaslaborales',
            name='observaciones_veracidad_documentos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
