# Generated by Django 5.0.6 on 2024-09-25 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat001Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('sigla', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'ESTADO',
                'verbose_name_plural': 'ESTADOS',
                'db_table': 'cat_001_estado',
            },
        ),
        migrations.CreateModel(
            name='Cat004Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('departamento_id_003', models.IntegerField(blank=True, null=True)),
                ('estado_id_001', models.ForeignKey(db_column='estado_id_001', on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat001estado')),
            ],
            options={
                'verbose_name': 'CIUDAD',
                'verbose_name_plural': 'CIUDADES',
                'db_table': 'cat_004_ciudad',
            },
        ),
    ]
