# Generated by Django 5.0.6 on 2024-07-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat001estado',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cat001estado',
            name='sigla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cat004ciudad',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
