# Generated by Django 5.0.6 on 2026-03-19 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('usuarios', '0008_alter_usuariobase_imagen_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat005AsignacionQr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('estado_id_001', models.ForeignKey(db_column='estado_id_001', on_delete=django.db.models.deletion.DO_NOTHING, to='common.cat001estado')),
                ('grupo_asignacion', models.ForeignKey(db_column='grupo_asignacion', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.grupo')),
                ('usuario_asignado', models.ForeignKey(db_column='usuario_asignado', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
