# Generated by Django 5.0.6 on 2026-03-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_add_qr_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat005asignacionqr',
            options={'verbose_name': 'ASIGNACION_QR', 'verbose_name_plural': 'ASIGNACIONES_QR'},
        ),
        migrations.AlterModelTable(
            name='cat005asignacionqr',
            table='cat_005_asignacion_qr',
        ),
    ]
